In [5]:
# import cv2

# img_src = cv2.imread('C:/Users/stephanie/Downloads/contamJuneOut/1a0ceabf-ed23-11ec-884c-b0a4605c76c2.png',0)
# print(img_src)

# img = cv2.imread('C:/Users/stephanie/Downloads/contamJuneOut/1a0ceabf-ed23-11ec-884c-b0a4605c76c2.png')
  
# # cv2.imread() -> takes an image as an input
# h, w, channels = img.shape
  
# half = w//2
  
  
# # this will be the first column
# left_part = img[:, :half] 
  
# # [:,:half] means all the rows and
# # all the columns upto index half
  
# # this will be the second column
# right_part = img[:, half:]  
  
# # [:,half:] means al the rows and all
# # the columns from index half to the end
# # cv2.imshow is used for displaying the image
# cv2.imshow('Left part', left_part)
# cv2.imshow('Right part', right_part)
  
# # this is horizontal division
# half2 = h//2
  
# top = img[:half2, :]
# bottom = img[half2:, :]
  
# cv2.imshow('Top', top)
# cv2.imshow('Bottom', bottom)
  
# # saving all the images
# # cv2.imwrite() function will save the image 
# # into your pc
# cv2.imwrite('top.jpg', top)
# cv2.imwrite('bottom.jpg', bottom)
# cv2.imwrite('right.jpg', right_part)
# cv2.imwrite('left.jpg', left_part)
# cv2.waitKey(0)

[[74 73 71 ... 16 16 16]
 [74 73 71 ... 16 16 16]
 [74 73 71 ... 16 16 16]
 ...
 [41 42 42 ... 17 18 19]
 [41 41 41 ... 17 17 17]
 [41 41 40 ... 16 17 17]]


error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1268: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'


In [34]:
# importing Image class from PIL package
from PIL import Image
import uuid
import numpy as np

# opening a multiband image (RGB specifically)
im = Image.open(r"C:/Users/stephanie/Downloads/contamJuneOut/1b3237eb-ed23-11ec-8fc5-b0a4605c76c2.png")

# split() method
# this will split the image in individual bands
# and return a tuple
im1 = Image.Image.split(im)
  
# showing each band
im1[0].show()
im1[1].show()
im1[2].show()

# im1[0].save("im1_0", "JPG")
# im1[1].save("im1_1", "JPG")
# im1[2].save("im1_2", "JPG")

# cv2.imwrite('C:/Users/stephanie/Downloads/'+ str(uuid.uuid1()) + '.png', im1[0])
# cv2.imwrite('C:/Users/stephanie/Downloads/'+ str(uuid.uuid1()) + '.png', im1[1])
# cv2.imwrite('C:/Users/stephanie/Downloads/'+ str(uuid.uuid1()) + '.png', im1[2])

###code to get the coloured channels

In [31]:
from PIL import Image

img = Image.open('C:/Users/stephanie/Downloads/contamJuneOut/1b3237eb-ed23-11ec-8fc5-b0a4605c76c2.png')
data = img.getdata()

# Suppress specific bands (e.g. (255, 120, 65) -> (0, 120, 0) for g)
r = [(d[0], 0, 0) for d in data]
g = [(0, d[1], 0) for d in data]
b = [(0, 0, d[2]) for d in data]

img.putdata(r)
img.save('r.png')
img.putdata(g)
img.save('g.png')
img.putdata(b)
img.save('b.png')

Code to resize

In [7]:
# let's start with the Imports 
import cv2
import numpy as np
import uuid
import os

folder = 'C:/Users/stephanie/Downloads/contamJuneToResize'

for fileName in os.listdir(folder):
    print(fileName)

    image = cv2.imread('C:/Users/stephanie/Downloads/contamJuneToResize/' + fileName)

# Read the image using imread function
# image = cv2.imread('C:/Users/stephanie/Downloads/contamJuneOut/1b3237eb-ed23-11ec-8fc5-b0a4605c76c2.png')
# cv2.imshow('Original Image', image)

# let's downscale the image using new  width and height
    down_width = 100
    down_height = 100
    down_points = (down_width, down_height)
    resized_down = cv2.resize(image, down_points, interpolation= cv2.INTER_LINEAR)

# let's upscale the image using new  width and height
# up_width = 600
# up_height = 400
# up_points = (up_width, up_height)
# resized_up = cv2.resize(image, up_points, interpolation= cv2.INTER_LINEAR)

# Display images
# cv2.imshow('Resized Down by defining height and width', resized_down)
# cv2.waitKey()
# cv2.imshow('Resized Up image by defining height and width', resized_up)
# cv2.waitKey()

    cv2.imwrite('C:/Users/stephanie/Downloads/resized/'+ str(uuid.uuid1()) + '100x100' + '.png', resized_down)
print('done with resizing')
#press any key to close the windows
# cv2.destroyAllWindows()

bottom-leftheight100px.png
bottom-rightheight100px.png
Slice 371.png
Slice 3710.png
Slice 3711.png
Slice 3712.png
Slice 3713.png
Slice 3714.png
Slice 3715.png
Slice 3716.png
Slice 3717.png
Slice 3718.png
Slice 3719.png
Slice 372.png
Slice 3720.png
Slice 3721.png
Slice 3722.png
Slice 3723.png
Slice 3724.png
Slice 3725.png
Slice 3726.png
Slice 3727.png
Slice 3729.png
Slice 373.png
Slice 3730.png
Slice 3731.png
Slice 3732.png
Slice 374.png
Slice 375.png
Slice 376.png
Slice 377.png
Slice 378.png
Slice 379.png
Slice 391.png
Slice 3910.png
Slice 3911.png
Slice 3912.png
Slice 3913.png
Slice 3914.png
Slice 3915.png
Slice 3916.png
Slice 3917.png
Slice 3918.png
Slice 3919.png
Slice 392.png
Slice 3920.png
Slice 3921.png
Slice 3922.png
Slice 3923.png
Slice 3924.png
Slice 3925.png
Slice 3926.png
Slice 3927.png
Slice 3929.png
Slice 393.png
Slice 3930.png
Slice 3931.png
Slice 3932.png
Slice 394.png
Slice 395.png
Slice 396.png
Slice 397.png
Slice 398.png
Slice 399.png
Slice 411.png
Slice 4110.png
Slic